### ISSUE TITLE
What is the correct separator character to use when using sublevel v6?

### ISSUE THREAD

**Issue by theChumpus** [juliangruber/level-sublevel-stream#1]
Hi,

I'm having some problems detecting sublevels using the latest version of sublevel (i'm using 6.4.6). 

Instead of using the separator '\xff', sublevel now seems to use '!' to distinguish between sublevels. I've tried forcing this separator using the opts.sep property but to no avail.

Do you know what character/string to use please?

Thanks

**Comment by juliangruber** [comment]
That is most likely because sublevel v6 behaves differntly and thus the "hack" level-sublevel-stream employs doesn't work. unfortunately i don't have time to work on this problem at the moment, so you probably need to dig into this lib or find another solution.

**Comment by theChumpus** [comment]
Ok, no worries. I'll let you know if I find anything useful.
